import { defineConfig } from "vitest/config";

/**
 * What `npm test` at the repository root means.
 *
 * Without this, vitest walks the whole tree and collects anything that
 * looks like a test, including `apps/agentcore/agentcore/cdk/test`, which
 * is a Jest suite inside the CDK project the AgentCore CLI generates. That
 * project has its own package.json, its own dependencies and its own test
 * runner, so collecting it from here fails on an unresolvable
 * `aws-cdk-lib` import and takes the whole run down with it.
 *
 * Found by running `npm test` from a clean clone, which is the only way to
 * see what a reviewer sees.
 */
export default defineConfig({
  test: {
    include: [
      "apps/backend/test/**/*.test.ts",
      "apps/eval/test/**/*.test.ts",
      "packages/**/test/**/*.test.ts",
    ],
    exclude: [
      "**/node_modules/**",
      "**/dist/**",
      "**/cdk.out/**",
      // Generated by `agentcore create`; it is its own project and runs
      // under its own runner. See apps/agentcore/README.md.
      "apps/agentcore/**",
    ],
  },
});
